# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         mogilefs-server
version:      1.00
version_from: 
installdirs:  site
requires:
    Danga::Socket:                 1.22
    fields:                        0
    Getopt::Long:                  0
    Linux::AIO:                    1.3
    Perlbal:                       0
    Symbol:                        0
    Sys::Syslog:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
