# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MogileFS
version:      1.00
version_from: 
installdirs:  site
requires:
    fields:                        0
    IO::WrapTie:                   2.102
    LWP::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
